### ISSUE TITLE
Crash when launch arguments missing

### ISSUE THREAD

**Issue by quixoft** [CosmicPi/cosmicpi-daq#11]
python ./cosmicpi-daq.py -u /dev/ttyACM0

This launch crashes the program. The defaults should be set correctly and errors handled with a proper error message ....

Pleas supply a valid server port

**Comment by juzsal** [comment]
Good, thanks for reporting. Will push a fix soon.

**Comment by quixoft** [comment]
julian@TTLeaz:~/git-pi/cosmicpi-daq$ python ./cosmicpi-daq.py

options (Server IP address)     ip   : localhost
options (Server Port number)    port : 5672
options (USB device name)       usb  : /dev/ttyACM0
options (Logging directory)     odir : /tmp
options (Event logging)         log  : False
options (UDP sending)           udp  : True
options (Vibration monitor)     vib  : False
options (Weather Station)       wst  : False
options (Cosmic Ray Station)    cray : True
options (Push notifications)    patk : 
options (Debug Flag)            debug: False

cosmic_pi monitor running, hit '>' for commands

Traceback (most recent call last):
  File "./cosmicpi-daq.py", line 367, in <module>
    main()
  File "./cosmicpi-daq.py", line 122, in main
    sio = Socket_io(host, port, username, password)
  File "/home/julian/git-pi/cosmicpi-daq/sock.py", line 10, in **init**
    credentials=pika.PlainCredentials(username, password)))
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 339, in **init**
    self._process_io_for_connection_setup()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 374, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 410, in _flush_output
    self._impl.ioloop.poll()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 602, in poll
    self._process_fd_events(fd_event_map, write_only)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 443, in _process_fd_events
    handler(fileno, events, write_only=write_only)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 364, in _handle_events
    self._handle_read()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 407, in _handle_read
    return self._handle_error(error)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 338, in _handle_error
    self._handle_disconnect()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 288, in _handle_disconnect
    self._adapter_disconnect()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 95, in _adapter_disconnect
    super(SelectConnection, self)._adapter_disconnect()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 154, in _adapter_disconnect
    self._check_state_on_disconnect()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 173, in _check_state_on_disconnect
    raise exceptions.ProbableAuthenticationError
pika.exceptions.ProbableAuthenticationError

**Comment by juzsal** [comment]
Good catch. Added another commit to the PR to address that.
